// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AI_Studio
{
    internal sealed partial class Vsix
    {
        public const string Id = "AI_Studio.8fa1980c-d304-499f-8faa-8f0623f4431b";
        public const string Name = "AI_Studio";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Emrah Kondur";
        public const string Tags = "";
    }
}
