// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AI_Studio
{
    internal sealed partial class Vsix
    {
        public const string Id = "AI_Studio.74F4FED3-20F1-4F08-BEC5-1219C8EDC2AD";
        public const string Name = "AI Studio";
        public const string Description = @"AI Studio helps you with the power of chatGPT in many subjects such as adding unit tests, refactoring code, adding summary, etc. while writing code, just by right click on the code.";
        public const string Language = "en-US";
        public const string Version = "1.2.0";
        public const string Author = "Emrah Kondur";
        public const string Tags = "AI, chatGPT, UnitTest, Refactor, Summary, OpenAI";
    }
}
