// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AI_Studio
{
    internal sealed partial class Vsix
    {
        public const string Id = "AI_Studio.8fa1980c-d304-499f-8faa-8f0623f4431b";
        public const string Name = "AI Studio";
        public const string Description = @"AI Studio helps you with the power of chatGPT in many subjects such as adding unit tests, refactor code, adding summary etc. while writing code.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Emrah Kondur";
        public const string Tags = "AI, chatGPT, UnitTest, Refactor, Summary";
    }
}
