// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AI_Studio
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AI_StudioString = "2dd7016f-e0cf-41b5-bc1a-ca24bd6b9662";
        public static Guid AI_Studio = new Guid(AI_StudioString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AI_MenuGroup = 0x1000;
        public const int AI_CommandGroup = 0x1001;
        public const int AI_Menu = 0x1002;
        public const int AddUnitTests = 0x0000;
        public const int AddSummary = 0x0001;
        public const int AddComments = 0x0002;
        public const int Refactor = 0x0003;
        public const int Explain = 0x0004;
    }
}